Update ViewController.swift
FirebaseExtended/analytics-webview pull request #3
Opened 2017-08-31 18:24 UTC by Fallenstedt

With release of cocoapod Firebase 4.1.1, FIRAnalytics has been renamed to Analytics. withName is now an extraneous argument.

2017-08-31 18:25 UTC, Fallenstedt commented
I signed it!

2017-08-31 18:26 UTC, samtstern commented
cc @morganchen12

2017-08-31 18:44 UTC, morganchen12 requested changes
Looks good aside from a few nits. Thanks for doing this!

2017-08-31 18:44 UTC, morganchen12 commented on ios/swift/FirebaseAnalyticsWeb/ViewController.swift
> +                           didReceive message: WKScriptMessage) {
Please fix the inconsistent spacing in this file.

2017-08-31 19:34 UTC, Fallenstedt reviewed
I believe I have fixed the spacing.

2017-08-31 20:25 UTC, morganchen12 commented
Thanks!

@samtstern it seems I don't have push access, can you merge this and/or add me?

2017-09-13 23:21 UTC, Fallenstedt commented
Bumping. It's been 13 days.

2017-09-14 00:33 UTC, samtstern commented
Oh wow this is totally my fault!  I did not see that I was blocking this.  Thanks @Fallenstedt for bumping and sorry for the delay.

2017-09-14 00:33 UTC, merged